name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: guardian_nexus/guardian_nexus/package.json

      - name: Install dependencies
        working-directory: guardian_nexus/guardian_nexus
        run: npm ci

      - name: Build
        working-directory: guardian_nexus/guardian_nexus
        env:
          VITE_BASE: /destiny2-companion-app/
        run: npm run build

      - name: Add SPA 404 fallback
        run: |
          cp guardian_nexus/guardian_nexus/build/index.html guardian_nexus/guardian_nexus/build/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: guardian_nexus/guardian_nexus/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


